jobmanager.rpc.address: jobmanager
taskmanager.numberOfTaskSlots: 4
blob.server.port: 6124
jobmanager.rpc.port: 6123
taskmanager.rpc.port: 6122
jobmanager.memory.process.size: 1600m
taskmanager.memory.process.size: 4096m
parallelism.default: 1query.server.port: 6125
query.server.port: 6125
