# JobManager 地址和端口
jobmanager.rpc.address: jobmanager
jobmanager.rpc.port: 6123
jobmanager.memory.process.size: 1600m

# TaskManager 设置
taskmanager.numberOfTaskSlots: 4
taskmanager.memory.process.size: 4096m
taskmanager.rpc.port: 6122

# BLOB 服务端口
blob.server.port: 6124

# 默认并行度
parallelism.default: 1

# SQL Gateway 端口（用于 Flink SQL）
query.server.port: 6125
