services:
  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z
    container_name: minio
    ports:
      - "9000:9000"     # S3 API 端口
      - "9001:9001"     # 管理界面端口
    volumes:
      - ./data:/data    # 挂载本地的 ./data 目录到容器中的 /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin@123
    command:
      - server
      - /data
      - --console-address
      - :9001
    restart: unless-stopped